### PR TITLE
Shut down kernel after notebook execution

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Review by rra — COMMENTED** [review]
Don't you need to do this in `NotebookRunner`? This seems to change only the simple loop.

**Comment by athornton** [comment]
> Don't you need to do this in `NotebookRunner`? This seems to change only the simple loop.

No, I'm not putting a count in NotebookRunner, I'm just doing a new kernel per complete notebook.  For the not-in-a-notebook executor I can't do that, hence MAX_EXECUTIONS.

**Review by rra — COMMENTED** [review]
I'm confused, then, because I don't think we've seen the problem with this runner, and we've definitely seen the problem with the `NotebookRunner`. So I'm not sure how this change can address the problem we're trying to fix.

**Review by rra — APPROVED** [review]
Oh, wait, never mind, I see, you're adding a delete to `NotebookRunner`. Somehow I missed that.

**Pull request merged**
